[package]
name = "quux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
shared = { path = "./shared" }
html = { path = "./html" }
wasm-bindgen = { workspace = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
axum = { version = "0.6", features = ["headers"]}
tokio = { workspace = true }

[workspace.dependencies]
wasm-bindgen = "0.2"
tokio = { version = "1", features = ["full"] }

[workspace]
members = [
    "html",
    "shared"
]
